### ISSUE TITLE
Use TC API to get machine information from taskcluster worker ID?

### ISSUE THREAD

**Issue by g-k** [mozilla-services/relops-hardware-controller#16]
Currently this service maintains a TaskclusterWorker to Machine relation in the DB to get the Machine host and IP for a TC worker id.

However, to avoid syncing data the RelOps team would like Taskcluster to be the single source of truth.

Ideally we would drop the TaskclusterWorker table and have the action endpoints:

1. accept all TC worker IDs
1. use a TC API to get information (say datacenter and IP) by worker ID (maybe with [getWorker](https://docs.taskcluster.net/reference/platform/taskcluster-queue/references/api#getWorker))
1. use the datacenter and IP to look up machine and infrastructure details (machine type, hypervisor, PDU, ssh creds, etc.)

@djmitche Does TC expose an API to get information like datacenter and IP by worker ID? Or is there a way to store that extra info about a worker in TC?

**Comment by djmitche** [comment]
We have talked about allowing declareWorker to store an arbitrary JSON blob, where you could put that data.  But right now that's not supported, no.

**Comment by g-k** [comment]
From the last meeting we should:

* construct a fqdn from TC Worker ID (see regex in puppet) and worker group datacenter id (mdc1, scl2)
* derive everything from fqdn (except PDU for the machine/device)
  * PDU info is in inventory and moving to infoblox which has an API (private IPs, out of band addresses, etc.) but short term jake will provide a config file

This data will be in flux short term while things get set up and longer term might change annually.
