### ISSUE TITLE
SNMP PDU reboot

### ISSUE THREAD

**Issue by g-k** [mozilla-services/relops-hardware-controller#8]
https://github.com/mozilla/build-slaveapi/blob/f2ef7726824908c0581dd4c622f231670e227db4/slaveapi/clients/pdu.py

**Comment by g-k** [comment]
@mozbhearsum @dividehex Trying to figure out what format [the PDU port](https://github.com/mozilla/build-slaveapi/blob/f2ef7726824908c0581dd4c622f231670e227db4/slaveapi/clients/pdu.py#L49) takes. Can you give me an example or point to one?

**Comment by mozbhearsum** [comment]
I honestly have no memory of that code. @callek may be able to help.
